[general]
verbose = true
bp_merge = 5_000
bp_wg_window = 10_000_000

[cov]
n_zscores_low = 3.5
n_zscores_high = 3.5
ratio_misjoin = 0.01
ratio_collapse = 1.5
ratio_false_dupe = 0.5

[mismatch]
n_zscores_high = 3.5
ratio_het = 0.2

[indel]
n_zscores_high = 10.0
min_ins_size = 20
min_del_size = 20
ratio_indel = 0.25

[softclip]
n_zscores_high = 3.5
ratio_softclip = 0.5

[group_by_ani]
window_size = 5_000
min_grp_size = 100_000
min_ident = 80.0

[repeat]
check_types = ["Misjoin", "Indel", "FalseDupe"]
ratio_repeat = 0.5
bp_extend = 5
