name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11', '3.12']
    steps:
    - name: Checkout directory.
      uses: actions/checkout@v3

    - name: Set up Python.
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.version }}

    - name: Install dependencies.
      run: |
        make venv && make build && make install

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11', '3.12']
    steps:
    - name: Checkout directory.
      uses: actions/checkout@v3
      with:
        lfs: 'true'

    - name: Set up Python.
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.version }}

    - name: Install dependencies.
      run: |
        make venv && make build
        venv/bin/python -m pip install -r requirements-dev.txt

    - name: Run tests.
      run: |
        source venv/bin/activate
        make test
